client_id     = "157867123348-mtlfqjt4klas4d6tgl42ujdrvg6u5db9.apps.googleusercontent.com"
client_secret = "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"
redirect_uri  = "https://systeme-complexe-gpnqeejyqc5cbxsykqzyn6.streamlit.app"
